# Generated by Django 4.1.4 on 2022-12-23 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='sent_at',
            new_name='timestamp',
        ),
    ]
